### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by Derson5** [minimalchaos/git-it#1]
Hi,

I didn`t know how to contact you, so I make this issue. You make issue in Kiko theme https://github.com/gfjaru/Kiko/issues/5. I wanted to know, how you do this. Can you please publish code for tags, archive etc like you do in http://pointless.surge.sh?

**Comment by Derson5** [comment]
Never mind.

**Comment by minimalchaos** [comment]
I asked the original developer to add it but he didn't allow it.

**Comment by Derson5** [comment]
Thanks for response. Yes, I saw your PR in his github account, thats why I tried to contact you in your account. I copied from other project tags and archive, and I wanted to compare with your code. If this is not a problem, I wanted to ask you to send the code as PR to my account: https://github.com/Derson5/Kiko
